[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts', '@chainlink/contracts/=node_modules/@chainlink/contracts',
'@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip','@solmate/contracts=lib/solmate/src', '@chainlink/test-contracts-ccip/=lib/ccip/contracts/src/v0.8/ccip/test']
ffi = true
fs_permissions = [{ access = "read", path = "./broadcast" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
